/* Matbakh — seasonal visual test layer v7 */
(function(){
  'use strict';
  const params=new URLSearchParams(location.search);
  const requested=params.get('season-test');
  const isTest=requested==='autumn'||requested==='halloween';
  if(!isTest) return;
  const rootClass='seasonal-test-'+requested;
  const esc=s=>String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]));
  const norm=s=>String(s??'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' ').trim();
  let stockCache=[];
  function installTheme(){document.body.dataset.seasonTest=requested;document.body.classList.add(rootClass);let link=document.getElementById('seasonalTestStyles');if(!link){link=document.createElement('link');link.id='seasonalTestStyles';link.rel='stylesheet';link.href='./seasonal-test.css?v=seasonal-test-v7';document.head.appendChild(link)}else link.href='./seasonal-test.css?v=seasonal-test-v7'}
  function getHome(){return document.getElementById('home')||document.querySelector('[data-view="home"]')}
  function getOriginalMeals(home){if(!home)return [];return [...home.querySelectorAll('.meal-slot')].slice(0,2).map((row,i)=>({icon:row.querySelector(':scope > span')?.textContent?.trim()||(i===0?'☀️':'🌙'),name:row.querySelector('button:not(.btn)')?.textContent?.trim()||row.textContent.replace(/\s+/g,' ').trim()||(i===0?'Déjeuner':'Dîner'),button:row.querySelector('button:not(.btn)')}))}
  function publicLabel(){return requested==='halloween'?'Halloween':'Automne'}
  function build(){
    const home=getHome();if(!home)return false;installTheme();const existing=document.getElementById('seasonalTestHome');const meals=getOriginalMeals(home);home.classList.add('seasonal-original-home');if(existing)existing.remove();
    const stage=document.createElement('section');stage.id='seasonalTestHome';stage.className='seasonal-test-home';stage.setAttribute('aria-label','Accueil Matbakh — test saisonnier');
    stage.innerHTML=`<header class="st-header"><div class="st-brand-wrap"><div class="st-brand">مَطْبَخ <span>♥</span></div><div class="st-subtitle">Carnet de cuisine de la maison</div></div><div class="st-header-actions"><button class="st-icon" data-action="swap" aria-label="Changer de saison">↔</button><button class="st-icon" data-action="theme" aria-label="Thème">${requested==='halloween'?'🎃':'🌿'}</button><button class="st-icon" data-action="save" aria-label="Sauvegarder">▣</button></div></header><main class="st-main"><section class="st-hero"><div class="st-hero-top"><span>VOTRE CUISINE, AU FIL DES SAISONS</span><b>${publicLabel()}</b></div><div class="st-hero-brand">مَطْبَخ</div><h1>Bonjour !</h1><p>Prête à cuisiner aujourd'hui ?</p></section><section class="st-shortcuts"><button data-view="recipes"><span class="st-shortcut-icon">▤</span><strong>Mes recettes</strong></button><button data-view="stock"><span class="st-shortcut-icon">▥</span><strong>Mon stock</strong></button><button data-view="shopping"><span class="st-shortcut-icon">▦</span><strong>Ma liste de courses</strong></button><button data-view="cakes"><span class="st-shortcut-icon">♨</span><strong>Mes gâteaux</strong></button></section><section class="st-today"><div class="st-today-head"><h2>Aujourd'hui</h2><span>${new Intl.DateTimeFormat('fr-FR',{day:'numeric',month:'long'}).format(new Date())}</span></div><div class="st-meals">${meals.length?meals.map((m,i)=>`<button class="st-meal" data-original-meal="${i}"><span class="st-meal-icon">${esc(m.icon)}</span><span class="st-meal-copy"><strong>${esc(m.name)}</strong><small>🟢 Tout est disponible</small></span><span class="st-chevron">›</span></button>`).join(''):`<div class="st-empty">Aucun repas prévu aujourd'hui.</div>`}</div><button class="st-program" data-action="program">Voir mon programme</button></section></main><nav class="st-bottom-nav" aria-label="Navigation principale"><button class="active" data-action="home"><span>⌂</span><small>Accueil</small></button><button data-view="meals"><span>♧</span><small>Repas</small></button><button data-view="recipes"><span>▤</span><small>Recettes</small></button><button data-view="stock"><span>▥</span><small>Stock</small></button><button data-view="shopping"><span>⌑</span><small>Courses</small></button></nav>`;
    home.parentNode.insertBefore(stage,home);stage.querySelectorAll('[data-view]').forEach(btn=>btn.addEventListener('click',()=>{const view=btn.dataset.view;if(typeof window.setView==='function')window.setView(view);else home.querySelector(`[data-view="${view}"]`)?.click()}));stage.querySelectorAll('[data-original-meal]').forEach(btn=>btn.addEventListener('click',()=>meals[Number(btn.dataset.originalMeal)]?.button?.click()));stage.querySelector('[data-action="program"]')?.addEventListener('click',()=>{if(typeof window.setView==='function' )window.setView('meals')});stage.querySelector('[data-action="home"]')?.addEventListener('click',()=>{if(typeof window.setView==='function')window.setView('home')});return true;
  }
  function showSplash(){if(sessionStorage.getItem('matbakh-seasonal-splash-v7'))return;sessionStorage.setItem('matbakh-seasonal-splash-v7','1');const old=document.getElementById('seasonalTestSplash');if(old)old.remove();const splash=document.createElement('div');splash.id='seasonalTestSplash';splash.className='st-splash';splash.innerHTML=`<div class="st-splash-card"><div class="st-chef"></div><div class="st-splash-title">مَطْبَخ <span>♥</span></div><p>Votre cuisine,<br>au fil des saisons ♥</p><div class="st-progress"><i></i></div></div>`;document.body.appendChild(splash);setTimeout(()=>splash.classList.add('is-done'),1450);setTimeout(()=>splash.remove(),1850)}
  function readStock(){return new Promise(resolve=>{try{const req=indexedDB.open('mamouni-v1',3);req.onsuccess=()=>{const db=req.result;try{const tx=db.transaction('stock','readonly'),r=tx.objectStore('stock').getAll();r.onsuccess=()=>{stockCache=Array.isArray(r.result)?r.result:[];db.close();resolve(stockCache)};r.onerror=()=>{db.close();resolve(stockCache)}}catch{db.close();resolve(stockCache)}};req.onerror=()=>resolve(stockCache)}catch{resolve(stockCache)}})}
  function sortMealRecipeSelect(select){if(!select||select.dataset.sortedV5)return;const selected=select.value;const opts=[...select.options].sort((a,b)=>a.textContent.localeCompare(b.textContent,'fr',{sensitivity:'base'}));select.replaceChildren(...opts);select.value=selected;select.dataset.sortedV5='1'}
  function canonicalFromStock(name){const n=norm(name);return stockCache.find(s=>norm(s.name)===n)?.name||name.trim()}
  function unitForStock(name,current){const s=stockCache.find(x=>norm(x.name)===norm(name));return s?.unit||current}
  function addStockItem(name,unit){const clean=canonicalFromStock(name);if(!clean||stockCache.some(s=>norm(s.name)===norm(clean)))return;try{const req=indexedDB.open('mamouni-v1',3);req.onsuccess=()=>{const db=req.result;const tx=db.transaction('stock','readwrite');tx.objectStore('stock').put({id:'s'+Date.now()+Math.random(),name:clean,qty:0,unit:unit||'unit',category:'Autres',subcategory:''});tx.oncomplete=()=>{db.close();readStock()};tx.onerror=()=>db.close()}}catch{}}
  function enhanceRecipeIngredients(){const editor=document.getElementById('ingredientEditor');if(!editor)return;readStock().then(()=>{[...editor.querySelectorAll('.ingredient-line')].forEach(line=>{if(line.dataset.assistV5)return;line.dataset.assistV5='1';const name=line.querySelector('.ing-name'),unit=line.querySelector('.ing-unit');if(!name||!unit)return;const wrap=document.createElement('div');wrap.className='st-ing-assist';const select=document.createElement('select');select.className='st-stock-suggestion';select.innerHTML='<option value="">Suggestions de mon stock…</option>'+[...stockCache].sort((a,b)=>{const ca=String(a.category||'Autres').localeCompare(String(b.category||'Autres'),'fr',{sensitivity:'base'});return ca||a.name.localeCompare(b.name,'fr',{sensitivity:'base'})}).map(s=>`<option value="${esc(s.name)}">${esc(s.name)} · ${esc(s.category||'Autres')} · ${esc(s.unit||'unit')}</option>`).join('');select.addEventListener('change',()=>{if(!select.value)return;name.value=select.value;unit.value=unitForStock(select.value,unit.value);name.dispatchEvent(new Event('input',{bubbles:true}))});wrap.appendChild(select);line.insertBefore(wrap,name);name.addEventListener('blur',()=>{const canonical=canonicalFromStock(name.value);if(canonical!==name.value){name.value=canonical;unit.value=unitForStock(canonical,unit.value)}});const add=document.createElement('button');add.type='button';add.className='st-add-stock';add.textContent='＋ Stock';add.title='Ajouter cet ingrédient au stock avec quantité 0';add.addEventListener('click',()=>{addStockItem(name.value,unit.value);add.textContent='✓ Stock';setTimeout(()=>add.textContent='＋ Stock',1200)});line.appendChild(add)})})}
  function enhanceModal(){const mealForm=document.getElementById('mealForm');if(mealForm)sortMealRecipeSelect(mealForm.querySelector('select[name="recipe"]'));if(document.getElementById('ingredientEditor'))enhanceRecipeIngredients()}
  function boot(){installTheme();let tries=0;const tick=()=>{tries++;if(build()){showSplash();return}if(tries<60)setTimeout(tick,100)};tick();const observer=new MutationObserver(()=>{const home=getHome();const stage=document.getElementById('seasonalTestHome');if(home&&!stage)build();if(home&&home.classList.contains('active')){home.style.display='none';if(stage)stage.style.display='flex'}if(home&&!home.classList.contains('active')&&stage)stage.style.display='none';enhanceModal()});observer.observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['class','value']});document.addEventListener('focusin',e=>{if(e.target?.classList?.contains('ing-name'))enhanceRecipeIngredients()})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
